version: '3'
services:
  web:
    build: .
    image: php:8.2-apache
    container_name: apache_php
    ports:
      - "8080:80"
    volumes:
      - ./sorgenti:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge